eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    should-unregister-on-shutdown: false
    service-url:
      defaultZone: http://localhost:8761/eureka
